### ISSUE TITLE
unbound go module unbound conf  file parsing

### ISSUE THREAD

**Issue by ColdCanuck** [netdata/go.d.plugin#295]
A minor problem, the unbound go module chokes on my unbound.conf file. 

It can't grok the line  >>>>  local-zone: "24.168.192.in-addr.arpa" transparent  <<<<
as it expects it to be param: value, not param: value1 value2. This is a valid unbound.conf line .

This causes the following:

init.go:64 error on parsing config: yaml: line 84: did not find expected key, skipping parameters auto detection

A second issue is that it does not seem to follow include statements in the unbound config chain.

**Comment by ilyam8** [comment]
Yes, it doesnt follow include statements.

See
https://github.com/netdata/go.d.plugin/blob/7f7e7ba009132b3224fd1ebee279a95314be65fd/modules/unbound/init.go#L49-L56

I dont like `unbound.conf` file parsing in general since it is very fragile - file format is not `yaml` in fact and we cant parse it properly.

**Comment by ilyam8** [comment]
I think we need just to drop configuration file parser and let user to set all parameters manually. More problems then benefit. 

What do you think?

**Comment by ilyam8** [comment]
Or write some stupid parser that reads a file line by line and finds needed parametrs and extracts values and follows includes:
- statistics-cumulative
- control-enable
- control-interface
- control-port
- control-use-cert
- control-key-file
- control-cert-file


This doesnt look hard. @ColdCanuck what is your opinion about the whole reading config files thing? Worth or worthless?

cc @Ferrion.

**Comment by ColdCanuck** [comment]
I don't think its worth the effort... the external program is a moving target (although in this case the speeds are glacial) and the variations on the config would be quite large. The netdata config file appears to work fine.

 I would just put a big note that says netdata doesn't parse it and give some good examples of the valid netdata config files.

Thanks for the quick response and the effort to get this working.

**Comment by ilyam8** [comment]
@ColdCanuck since you are a unbound user (i am not).

See
> https://github.com/NLnetLabs/unbound/issues/123

If you could help it would be nice.

**Comment by Ferroin** [comment]
A large part of the reason that the original Python module had it was that it happened to work for the common case if the file was properly formatted and removed the need for the user to manually configure Netdata to monitor Unbound.  IOW, a simple `ex -c '%s/\t/    /g' -c 'wq' /etc/unbound/unbound.conf` and an appropriate ACL could eliminate any need for the user to set up Netdata at all other than ensuring the collector was enabled.

I'm kind of indifferent whether it should be kept in the Go module or not, but the easiest solution I see is to just teach it to grab the rest of the line after the `:` up to any `#` that might be present as the config value and trip whitespace. It's not very likely that a user will need multiple values on a line for any of the keys we care about, and even less likely that Unbound is going to change the config file format, so the only other thing that would be necessary for 'complete' support for what we're trying to grab would be handling of includes.

**Comment by ilyam8** [comment]
It would make sense if the file was readable without setting anything from user side. Moreover it is not the file it is files! - unbound config supports including. 

If we need user help to get it running then it is easier to ask user to set a job params then changing permissions/ACL.

Compare:
 - please make all your config files readable for netdata
 - please set ip, port, stuff in the config file

I would never do first as a user when there is 2nd option.

**Comment by Ferroin** [comment]
@ilyam8 I'd preferentially use the first because then if I change configuration of Unbound in a way that affects Netdata, Netdata will just pick it up on reload.  I also use a (mostly, except for openresolv support) monolithic config file for Unbound that has no sensitive information in it though, and I do get your argument about user effort.

Personally, I'd like to see the Go module at least handle the monolithic config file case like the Python module does (albeit without the indentation limitations), which as far as I can see should just require teaching it to assume everything from `:` up to EOL or `#` with spaces trimmed is the value, but I only think we should worry about feature parity here, and can probably (eventually) drop it.

**Comment by ilyam8** [comment]
ok, i think i fixed most of the problems, new parser follows rules from `man unbound.conf`

- Files can be included using the include: directive.
- It can appear anywhere, it accepts a single file name as argument.
- Processing continues as if the text  from  the included file was copied into the config file at that point. 
- Wildcards can be used to include multiple files.
