### ISSUE TITLE
fix portcheck

### ISSUE THREAD

**Issue by l2isbad** [netdata/go.d.plugin#36]

**Comment by l2isbad** [comment]
Hi @ccremer, i need your help here.

I am rewriting your `portcheck` module in `go`. 

charts (i added `Current State Duration`):
![screenshot_20181123_111856](https://user-images.githubusercontent.com/22274335/48933723-694e7780-ef12-11e8-8872-39335226fd73.png)


I am interested in any input from you, since you are the author of python version and you are the user of this module (i am not). Should we add something to it or current implementation is ok? 

Current version uses only `tcp` for portcheck, should we add `udp`?

**Comment by l2isbad** [comment]
`telegraf` does something like that

>   Protocol, must be "tcp" or "udp"
>   NOTE: because the "udp" protocol does not respond to requests, it requires
>   a send/expect string pair (see below).

**Comment by l2isbad** [comment]
Or add it as additional module?

 * tcpcheck
 * udpcheck

looks clearer to me

@Wing924 What do you think?

**Comment by ccremer** [comment]
I like the idea of the new chart, it'll allow to calculate service uptimes :+1: 

Here's the thing with this plugin: I don't use it either xD The services I want to monitor have all a dedicated netdata plugin or I can do it with httpcheck. I created the plugin in order to check a generic service which doesn't have a netdata plugin. So you'll be able to check an arbitrary tcp service.

httpcheck is a specialized version of the portcheck. It knows how to read and write the packets so that we can extract data. But if you want to monitor an SSH server, the portcheck can do that in a limited manner too, unless we implement a dedicated ssh check plugin which could extract more data.

With keeping the portcheck as generic as possible, I don't know what metrics we could add without specializing for specific applications. I'm not sure whether we can differentiate between sending and receiving latencies. For the httpcheck, it might be interesting to find out where the bottleneck of a webapp is (network or rather processing requests etc).

UDP is another story. I did not implement udp simply because it would be very application specific, as responses are not guaranteed. I think it's a better approach to create dedicated plugins for each udp service (e.g. DNS, ...), though maybe a "base" framework/helper/whateveryoucallit could help reducing duplicate boilerplate code.

What are your thoughts on this?

**Comment by l2isbad** [comment]
> With keeping the portcheck as generic as possible
> I think it's a better approach to create dedicated plugins for each udp service (e.g. DNS, ...), though maybe a "base" framework/helper/whateveryoucallit could help reducing duplicate boilerplate code.

Agree, i'll rename it to `tcpcheck`. Like in [datadog](https://github.com/DataDog/integrations-core/tree/master/tcp_check).

We will add additional fucntionality later, the main goal for now is to move `python` version to `go`.

**Comment by ccremer** [comment]
yeah, that's a way better name^^
Looking forward to it :)

**Comment by ccremer** [comment]
I just realized we are moving towards a god plugin :D get it? go.d.plugin? I'll show myself out :P
