### ISSUE TITLE
`zookeeper`: SASL authentication

### ISSUE THREAD

**Issue by jrevillard** [netdata/go.d.plugin#432]
Dear all,

Currently, the zookeeper plug-in is able to connect to the Zk server without authentication or using TLS.
I need to connect to SASL (with TLS encryption) server and I think that this is not possible.

Best,
Jerome

**Comment by ilyam8** [comment]
Hi @jrevillard, indeed, there is no SASL auth support, i am dont even know what is SASL auth 😅 will check it!

**Comment by jrevillard** [comment]
Thanks for the quick answer @ilyam8 ... it's basically kerberos authentication using keytabs in my case :-). This is something which is practically the de facto standard in Big Data.

**Comment by ilyam8** [comment]
If you are still interested in this feature - consider [opening a feature request](https://github.com/netdata/netdata/issues/new?assignees=&labels=feature+request%2Cneeds+triage&template=FEAT_REQUEST.yml&title=%5BFeat%5D%3A+) in the netdata repo. Closing the issue because I plan to disable issues in this repo - will be using netdata/netdata.
