### ISSUE TITLE
httpcheck url accept an array

### ISSUE THREAD

**Issue by gotjoshua** [netdata/go.d.plugin#579]
Is it possible to add the possibility to add several urls to the same job?
the important thing is to have them on a single chart for easier comparison...

**Comment by ilyam8** [comment]
Hi @gotjoshua 

I understand the request and see the point - indeed, it makes sense to have all the URLs check stats in a single chart.

<details>
<summary>The problem is 'HTTP Check Status' chart has several dimensions (different statuses)</summary>

https://github.com/netdata/go.d.plugin/blob/f90d7ff39d052e3d8adb527ad6f4d68e07c71562/modules/httpcheck/charts.go#L38-L48

</details>

I don't know how to make that chart with several URLs 🤔 Any ideas?

**Comment by gotjoshua** [comment]
good point,
i'd actually use bars for all non success status and the lines for the
separate URLs

possible?

**Comment by ilyam8** [comment]
Hey, @gotjoshua.

If you are still interested in this feature - consider [opening a feature request](https://github.com/netdata/netdata/issues/new?assignees=&labels=feature+request%2Cneeds+triage&template=FEAT_REQUEST.yml&title=%5BFeat%5D%3A+) in the netdata repo.
