### ISSUE TITLE
Pkg/Socket proposal (unify socket client in the agent)

### ISSUE THREAD

**Issue by georgeok** [netdata/go.d.plugin#622]
In the agent we have more than one module that are using sockets, and they have their own implementations of TCP clients. 
I propose that we implement a socket client capable of handling TCP, UDP and Unix sockets in order to hide the complexity 
from the individual modules and have a unified way of dealing with socket to make the development of new modules easier.
Something similar to the `pkg/web` package that we have.

At a high level it should be able to send data `[]bytes` over a socket, wait and read the response if any.

Other requirement are:
- ability to handle timeouts
- tls
- ability to perform dns resolution internally of the target is a domain
- handle both IPv4 and IPv6
- have higher level functions to handle string slices
- supported buffered io for better networking performance
- 
An example interface of such a client can be:
```go
type Socket interface {
Connect() error
Disconnect() error
Read(p []byte) (n int, err error)
Write(p []byte) (n int, err error)
}
```
where the caller has to manage the connection and disconnection and call read write.

So that would be 
```go

s := socket{}
s.Connect()
defer s.Disconnect()
s.Write()
s.Read()
```

and/or we can offer some higher level functions
```go
type Socket interface {
	Command([]byte) ([]byte, error)
    CommandStr([]string) ([]string, error)
}
```
where the caller creates a new socket and call command() and the function internally 
figures out everything like DNS resolution, keep-alive, writing, reading, timeouts
and returns some bytes to the caller which then knows what to expect and coverts the
data to appropriate data types. This will also hide `Connect` in case we have `DGRAM` packets.
This is similar to the `fetch()` method in the `zookeeper` module

Maybe we can also support plain packet or ICMP as well, but I don't see much benefit yet for these,
unless we have some modules in mind.

Most of the code can be extracted directly from our `zookeeper` module also be used elsewhere in the future.

Modules that use their own tcp/udp clients:
- zookeeper
- openvpn
- phpfpm
- unbound
and maybe I am missing some more.

Please let me know what your thoughts are

**Comment by ilyam8** [comment]
Yeah, according to current usage, we need something simple:
 - no connection pools
 - no need to handle concurrency

Few notes:
 - I see we have [readLinesLimit](https://github.com/netdata/go.d.plugin/blob/bdf893a8c8227f4e28f674b57c57fd6ee84994fc/modules/zookeeper/client.go#L113-L114) (I don't remember why I add it, but there was a reason (i believe so 😄 ), so we need to keep it).
 - sometimes it is required to close the socket after sending a command, e.g. [unbound](https://github.com/NLnetLabs/unbound/blob/master/doc/control_proto_spec.txt)

> Server executes command. And sends reply in ascii text over channel, closes the channel when done.

I agree that it would be nice to hide Connect and do it when we execute SendCommand first time, but anyway we need to call Disconnect explicitly during Cleanup.

 - since we don't need concurrency we need to reuse the buffer. Could be the socket client option, like csv.Reader

> 	// ReuseRecord controls whether calls to Read may return a slice sharing
	// the backing array of the previous call's returned slice for performance.
	// By default, each call to Read returns newly allocated memory owned by the caller.
	ReuseRecord bool

---

Considering all the above we could make a module responsible for consuming response lines **as we read them**
- in that way we don't need 2 sets of methods (methodName, methodNameStr).
- don't need buffers
- the module defines when to stop reading response, etc.
 
Just an example code to show the gist

```go
type Socket interface {
	SendCommand(command string, process Processor) error
}

type Processor func([]byte) bool

func (sc SocketClient) read(r io.Reader, p Processor) error {
	s := bufio.NewScanner(r)
	for s.Scan() {
        if !p(s.Bytes()) {
            break
        }
	}
	return s.Err()
}
```

What do you think?

**Comment by georgeok** [comment]
I like the idea of passing a processor as an argument. This will indeed save us of multiple methods and probably make testing easier. Maybe we can put some default processors for byte and string slices. 

Not keeping buffers around is also helpful for managing states and memory.

For the close method: This one is confusing a bit. I guess I will in 10 minutes of development I’ll know why.

Sounds like a plan. I’ll do a quick spike and a WIP PR so that we can track and settle all these issues.

**Comment by georgeok** [comment]
So I have made a PR for this #624. It's still marked as WIP, but I'd like to get some initial feedback before I polish the details. I've also made two example PRs (#626 and #627) to demonstrate how to use the new package for the zookeeper and unbound modules. 🙏Please let me know your though on the initial idea.
