### ISSUE TITLE
configurable run ctx

### ISSUE THREAD

**Issue by vahid-sohrabloo** [netdata/go.d.plugin#650]
Hi
I want to use the `agent` package on my own.
The run ctx is hard-coded, and it will be duplicated with `go.d.plugin``
https://github.com/netdata/go.d.plugin/blob/4c9b86c3aa1ba532de2c6b0950b59eaf1de8f3b7/agent/module/job.go#L22

**Comment by ilyam8** [comment]
Hi, @vahid-sohrabloo. Yeah, that chart context is hardcoded. 

We use it in the [go.d_job_last_collected_secs](https://github.com/netdata/netdata/blob/master/health/health.d/go.d.plugin.conf) health template. It allows to automatically create "the number of seconds since the last successful data collection" (basically data collection job availability) alarm for every job.

---

What would you expect it to be? `netdata.{pluginName}_execution_time`?

**Comment by vahid-sohrabloo** [comment]
Hi @ilyam8 
yes exacly.

**Comment by ilyam8** [comment]
Ok, we will fix it.
